spring:
  application:
    name: housekeep
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/applys?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: manager
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 3
      idle-timeout: 30000
      maximum-pool-size: 10
      connection-timeout: 30000
  redis:
    host: localhost
    port: 6379
    timeout: 5000
    client-type: lettuce
    lettuce:
      pool:
        max-active: 8
        max-wait: 10000
  cache:
    type: REDIS
    redis:
      time-to-live: 15m
      cache-null-values: false
      enable-statistics: true
      key-prefix: 'cache:${spring.application.name}:'
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.coolers.housekeep.housekeep.po